<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kRIQxfq' shared service.

return $this->privates['.service_locator.kRIQxfq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'lugarRepository' => ['privates', 'App\\Repository\\LugarRepository', 'getLugarRepositoryService.php', true],
], [
    'lugarRepository' => 'App\\Repository\\LugarRepository',
]);
