<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuxwxxG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuxwxxG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuxwxxG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuxwxxG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXuxwxxG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XuxwxxG',
    'container.build_id' => '3994fa6e',
    'container.build_time' => 1571503108,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuxwxxG');
