<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7UndAxW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7UndAxW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7UndAxW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7UndAxW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7UndAxW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7UndAxW',
    'container.build_id' => '9a7187b8',
    'container.build_time' => 1571593453,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7UndAxW');
