<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1wRBwaQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1wRBwaQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1wRBwaQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1wRBwaQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1wRBwaQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1wRBwaQ',
    'container.build_id' => '651b7702',
    'container.build_time' => 1571495809,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1wRBwaQ');
